name: fact2023
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pytorch
  - python=3.9
  - torchvision
  - tqdm
  - scikit-learn
  - cvxpy
  - opencv
  - onnx
  - graphviz
  - easydict
  - scikit-image
  - matplotlib
  - numpy=1.23.5
  - jupyter
  - seaborn
  - qt
